# Generated by Django 5.2.15 on 2026-06-12 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gmail_message_id", models.CharField(max_length=180, unique=True)),
                ("gmail_thread_id", models.CharField(blank=True, max_length=180)),
                ("subject", models.CharField(max_length=255)),
                ("sender", models.EmailField(blank=True, max_length=254)),
                ("received_at", models.DateTimeField()),
                ("body_text", models.TextField()),
                ("body_html", models.TextField(blank=True)),
                ("headers", models.JSONField(blank=True, default=dict)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("stored", "Stored"),
                            ("parsed", "Parsed"),
                            ("review_required", "Review required"),
                            ("failed", "Failed"),
                        ],
                        default="stored",
                        max_length=30,
                    ),
                ),
                ("processing_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raw_emails",
                        to="bookings.provider",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
    ]
