# Generated by Django 5.2.15 on 2026-06-13 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GmailSyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mailbox_email", models.EmailField(max_length=254, unique=True)),
                (
                    "latest_history_id",
                    models.CharField(blank=True, max_length=180, null=True),
                ),
                ("watch_expiration", models.DateTimeField(blank=True, null=True)),
                ("last_successful_sync", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["mailbox_email"],
            },
        ),
        migrations.CreateModel(
            name="RawEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gmail_message_id", models.CharField(max_length=180, unique=True)),
                (
                    "gmail_thread_id",
                    models.CharField(blank=True, max_length=180, null=True),
                ),
                (
                    "gmail_history_id",
                    models.CharField(blank=True, max_length=180, null=True),
                ),
                ("gmail_outer_sender", models.EmailField(max_length=254)),
                (
                    "original_forwarded_sender",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("subject", models.CharField(max_length=255)),
                ("received_at", models.DateTimeField()),
                ("body_text", models.TextField()),
                ("body_html", models.TextField(blank=True, null=True)),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("parsed", "Parsed"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored"),
                            ("needs_review", "Needs review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("parse_error", models.TextField(blank=True, null=True)),
                (
                    "parser_version",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider_detected",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raw_emails",
                        to="bookings.provider",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["gmail_thread_id"], name="raw_email_thread_idx"
                    ),
                    models.Index(fields=["received_at"], name="raw_email_received_idx"),
                    models.Index(
                        fields=["parse_status"], name="raw_email_parse_status_idx"
                    ),
                    models.Index(
                        fields=["provider_detected", "parse_status"],
                        name="raw_email_provider_status_idx",
                    ),
                ],
            },
        ),
    ]
