# Generated by Django 5.2.15 on 2026-06-12 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider_booking_reference", models.CharField(max_length=120)),
                (
                    "provider_order_reference",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            (
                                "pending_provider_acceptance",
                                "Pending provider acceptance",
                            ),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                            ("modified", "Modified"),
                            ("manual_review", "Manual review"),
                            ("parse_failed", "Parse failed"),
                            ("duplicate_ignored", "Duplicate ignored"),
                        ],
                        default="pending_provider_acceptance",
                        max_length=40,
                    ),
                ),
                ("raw_product_name", models.CharField(blank=True, max_length=240)),
                (
                    "raw_option_name",
                    models.CharField(blank=True, max_length=240, null=True),
                ),
                (
                    "provider_product_code",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "provider_option_code",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("provider_travel_date", models.DateField(blank=True, null=True)),
                ("provider_start_time", models.TimeField(blank=True, null=True)),
                ("provider_end_time", models.TimeField(blank=True, null=True)),
                (
                    "provider_slot_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fixed_time", "Fixed time"),
                            ("half_day", "Half day"),
                            ("full_day", "Full day"),
                            ("open_time", "Open time"),
                            ("private_group", "Private group"),
                        ],
                        max_length=30,
                    ),
                ),
                ("active_travel_date", models.DateField(blank=True, null=True)),
                ("active_start_time", models.TimeField(blank=True, null=True)),
                ("active_end_time", models.TimeField(blank=True, null=True)),
                (
                    "active_slot_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fixed_time", "Fixed time"),
                            ("half_day", "Half day"),
                            ("full_day", "Full day"),
                            ("open_time", "Open time"),
                            ("private_group", "Private group"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "provider_traveler_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "active_traveler_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "lead_traveler_name",
                    models.CharField(blank=True, max_length=180, null=True),
                ),
                (
                    "lead_traveler_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "lead_traveler_phone",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("traveler_names", models.JSONField(blank=True, default=list)),
                ("ticket_breakdown", models.JSONField(blank=True, default=dict)),
                ("language", models.CharField(blank=True, max_length=80, null=True)),
                ("pickup_location", models.TextField(blank=True, null=True)),
                ("meeting_point", models.TextField(blank=True, null=True)),
                ("special_requirements", models.TextField(blank=True, null=True)),
                ("customer_message", models.TextField(blank=True, null=True)),
                ("price", models.JSONField(blank=True, default=dict)),
                (
                    "payment_status",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "source_thread_id",
                    models.CharField(blank=True, max_length=180, null=True),
                ),
                ("last_email_received_at", models.DateTimeField(blank=True, null=True)),
                ("manual_override_fields", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": [
                    "-active_travel_date",
                    "active_start_time",
                    "provider_booking_reference",
                ],
            },
        ),
        migrations.CreateModel(
            name="CapacityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_from", models.DateField(blank=True, null=True)),
                ("date_to", models.DateField(blank=True, null=True)),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("slot_start_time", models.TimeField(blank=True, null=True)),
                ("slot_end_time", models.TimeField(blank=True, null=True)),
                ("capacity", models.PositiveIntegerField()),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["product_variant__product__canonical_name", "date_from"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("canonical_name", models.CharField(max_length=180, unique=True)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["canonical_name"],
            },
        ),
        migrations.CreateModel(
            name="ProductAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_product_name", models.CharField(max_length=240)),
                (
                    "raw_option_name",
                    models.CharField(blank=True, max_length=240, null=True),
                ),
                (
                    "provider_product_code",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "provider_option_code",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "confidence",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                ("approved", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["provider__name", "raw_product_name", "raw_option_name"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("variant_name", models.CharField(max_length=180)),
                (
                    "slot_type",
                    models.CharField(
                        choices=[
                            ("fixed_time", "Fixed time"),
                            ("half_day", "Half day"),
                            ("full_day", "Full day"),
                            ("open_time", "Open time"),
                            ("private_group", "Private group"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "default_capacity",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["product__canonical_name", "variant_name"],
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("code", models.SlugField(max_length=60, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("known_sender_patterns", models.JSONField(blank=True, default=list)),
                ("known_subject_patterns", models.JSONField(blank=True, default=list)),
                ("parser_key", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReviewQueueItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("provider_not_detected", "Provider not detected"),
                            ("reference_missing", "Reference missing"),
                            ("date_missing", "Date missing"),
                            ("time_missing", "Time missing"),
                            ("traveler_count_missing", "Traveler count missing"),
                            ("product_alias_missing", "Product alias missing"),
                            ("low_confidence_parse", "Low confidence parse"),
                            ("possible_duplicate", "Possible duplicate"),
                            ("manual_override_conflict", "Manual override conflict"),
                            (
                                "cancellation_without_booking",
                                "Cancellation without booking",
                            ),
                            ("parser_error", "Parser error"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("ignored", "Ignored"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("details", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["status", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("email_new_booking", "Email new booking"),
                            ("email_booking_request", "Email booking request"),
                            ("email_update", "Email update"),
                            ("email_cancellation", "Email cancellation"),
                            ("manual_edit", "Manual edit"),
                            ("manual_status_change", "Manual status change"),
                            ("parser_review_resolved", "Parser review resolved"),
                            ("product_alias_changed", "Product alias changed"),
                            ("conflict_detected", "Conflict detected"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("manual", "Manual"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="bookings.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
