# Generated by Django 5.2.15 on 2026-06-13 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("ingestion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingevent",
            name="raw_email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_events",
                to="ingestion.rawemail",
            ),
        ),
        migrations.AddIndex(
            model_name="provider",
            index=models.Index(fields=["code"], name="provider_code_idx"),
        ),
        migrations.AddIndex(
            model_name="provider",
            index=models.Index(fields=["active"], name="provider_active_idx"),
        ),
        migrations.AddField(
            model_name="booking",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="bookings.provider",
            ),
        ),
        migrations.AddField(
            model_name="provideralias",
            name="linked_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="provider_aliases",
                to="bookings.activityschedule",
            ),
        ),
        migrations.AddField(
            model_name="provideralias",
            name="linked_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="provider_aliases",
                to="bookings.activityscheduleslot",
            ),
        ),
        migrations.AddField(
            model_name="provideralias",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provider_aliases",
                to="bookings.provider",
            ),
        ),
        migrations.AddField(
            model_name="reviewqueueitem",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review_items",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="reviewqueueitem",
            name="raw_email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review_items",
                to="ingestion.rawemail",
            ),
        ),
        migrations.AddField(
            model_name="reviewqueueitem",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_review_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="touractivity",
            index=models.Index(fields=["active"], name="activity_active_idx"),
        ),
        migrations.AddIndex(
            model_name="touractivity",
            index=models.Index(
                fields=["category", "active"], name="activity_cat_active_idx"
            ),
        ),
        migrations.AddField(
            model_name="provideralias",
            name="linked_activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="provider_aliases",
                to="bookings.touractivity",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="bookings.touractivity",
            ),
        ),
        migrations.AddField(
            model_name="activityschedule",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="bookings.touractivity",
            ),
        ),
        migrations.AddField(
            model_name="activitypeoplerule",
            name="activity",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="people_rule",
                to="bookings.touractivity",
            ),
        ),
        migrations.AddIndex(
            model_name="activityscheduleslot",
            index=models.Index(
                fields=["schedule", "active"], name="act_slot_sched_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activityscheduleslot",
            index=models.Index(fields=["start_time"], name="activity_slot_start_idx"),
        ),
        migrations.AddIndex(
            model_name="activityscheduleslot",
            index=models.Index(fields=["slot_type"], name="activity_slot_type_idx"),
        ),
        migrations.AddIndex(
            model_name="bookingevent",
            index=models.Index(
                fields=["event_type", "created_at"], name="event_type_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingevent",
            index=models.Index(
                fields=["source", "created_at"], name="event_source_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewqueueitem",
            index=models.Index(
                fields=["issue_type", "status"], name="review_issue_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewqueueitem",
            index=models.Index(fields=["created_at"], name="review_created_idx"),
        ),
        migrations.AddIndex(
            model_name="provideralias",
            index=models.Index(
                fields=["provider", "raw_product_name"], name="alias_provider_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="provideralias",
            index=models.Index(
                fields=["provider", "provider_product_code"],
                name="alias_provider_code_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="provideralias",
            index=models.Index(fields=["approved"], name="alias_approved_idx"),
        ),
        migrations.AddIndex(
            model_name="provideralias",
            index=models.Index(
                fields=["needs_manual_confirmation"], name="alias_manual_confirm_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="provideralias",
            constraint=models.UniqueConstraint(
                fields=(
                    "provider",
                    "raw_product_name",
                    "raw_option_name",
                    "provider_product_code",
                    "provider_option_code",
                ),
                name="unique_provider_alias",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["active_travel_date"], name="booking_active_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="booking_status_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["activity", "active_travel_date"],
                name="booking_activity_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["schedule_slot", "active_travel_date"],
                name="booking_slot_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["provider", "status"], name="booking_provider_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["provider", "provider_order_reference"],
                name="booking_provider_order_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_booking_reference"),
                name="unique_provider_booking_reference",
            ),
        ),
        migrations.AddIndex(
            model_name="activityschedule",
            index=models.Index(
                fields=["activity", "schedule_kind"], name="activity_schedule_kind_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activityschedule",
            index=models.Index(
                fields=["date_from", "date_to"], name="activity_schedule_dates_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activityschedule",
            index=models.Index(fields=["active"], name="activity_schedule_active_idx"),
        ),
    ]
