# Generated by Django 5.2.15 on 2026-06-12 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("ingestion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingevent",
            name="raw_email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_events",
                to="ingestion.rawemail",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["canonical_name"], name="product_name_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "active"], name="product_category_active_idx"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="canonical_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="bookings.product",
            ),
        ),
        migrations.AddField(
            model_name="productalias",
            name="canonical_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="provider_aliases",
                to="bookings.product",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="bookings.product",
            ),
        ),
        migrations.AddField(
            model_name="productalias",
            name="canonical_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="provider_aliases",
                to="bookings.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="capacityrule",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capacity_rules",
                to="bookings.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="canonical_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="bookings.productvariant",
            ),
        ),
        migrations.AddIndex(
            model_name="provider",
            index=models.Index(fields=["code"], name="provider_code_idx"),
        ),
        migrations.AddIndex(
            model_name="provider",
            index=models.Index(fields=["active"], name="provider_active_idx"),
        ),
        migrations.AddField(
            model_name="productalias",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_aliases",
                to="bookings.provider",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="bookings.provider",
            ),
        ),
        migrations.AddField(
            model_name="reviewqueueitem",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review_items",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="reviewqueueitem",
            name="raw_email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review_items",
                to="ingestion.rawemail",
            ),
        ),
        migrations.AddField(
            model_name="reviewqueueitem",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_review_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="bookingevent",
            index=models.Index(
                fields=["event_type", "created_at"], name="event_type_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingevent",
            index=models.Index(
                fields=["source", "created_at"], name="event_source_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["product", "active"], name="variant_product_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["slot_type"], name="variant_slot_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                fields=("product", "variant_name"), name="unique_product_variant_name"
            ),
        ),
        migrations.AddIndex(
            model_name="capacityrule",
            index=models.Index(
                fields=["product_variant", "active"], name="capacity_variant_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="capacityrule",
            index=models.Index(
                fields=["date_from", "date_to"], name="capacity_date_range_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="capacityrule",
            index=models.Index(fields=["day_of_week"], name="capacity_day_idx"),
        ),
        migrations.AddIndex(
            model_name="productalias",
            index=models.Index(
                fields=["provider", "raw_product_name"], name="alias_provider_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productalias",
            index=models.Index(
                fields=["provider", "provider_product_code"],
                name="alias_provider_code_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productalias",
            index=models.Index(
                fields=["provider", "provider_option_code"],
                name="alias_provider_option_code_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productalias",
            index=models.Index(fields=["approved"], name="alias_approved_idx"),
        ),
        migrations.AddConstraint(
            model_name="productalias",
            constraint=models.UniqueConstraint(
                fields=(
                    "provider",
                    "raw_product_name",
                    "raw_option_name",
                    "provider_product_code",
                    "provider_option_code",
                ),
                name="unique_provider_product_alias",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["active_travel_date"], name="booking_active_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="booking_status_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["canonical_product", "active_travel_date"],
                name="booking_product_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["canonical_variant", "active_travel_date"],
                name="booking_variant_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["provider", "status"], name="booking_provider_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["provider", "provider_order_reference"],
                name="booking_provider_order_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_booking_reference"),
                name="unique_provider_booking_reference",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewqueueitem",
            index=models.Index(
                fields=["issue_type", "status"], name="review_issue_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewqueueitem",
            index=models.Index(fields=["created_at"], name="review_created_idx"),
        ),
    ]
