# Generated by Django 5.2.15 on 2026-06-13 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityschedule",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="activityschedule",
            name="recurrence_mode",
            field=models.CharField(
                choices=[
                    ("weekly", "Weekly"),
                    ("date_specific", "Date specific"),
                    ("manual", "Manual"),
                ],
                default="weekly",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ActivityScheduleException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exception_type",
                    models.CharField(
                        choices=[
                            ("blocked", "Blocked"),
                            ("closed", "Closed"),
                            ("override_capacity", "Override capacity"),
                            ("extra_slot", "Extra slot"),
                            ("removed_slot", "Removed slot"),
                        ],
                        max_length=40,
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="bookings.activityschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["schedule__activity__name", "date", "start_time", "id"],
                "indexes": [
                    models.Index(
                        fields=["schedule", "date", "active"],
                        name="schedule_exception_date_idx",
                    ),
                    models.Index(
                        fields=["exception_type", "active"],
                        name="schedule_exception_type_idx",
                    ),
                ],
            },
        ),
    ]
