# Generated by Django 5.2.15 on 2026-06-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="capacityrule",
            name="schedule_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="product",
            name="nickname",
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
