# Generated by Django 5.2.15 on 2026-06-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_activityschedule_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityscheduleslot",
            name="days_of_week",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
