# Generated by Django 5.2.15 on 2026-06-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_activityscheduleslot_days_of_week"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="attendance_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "CLEAR"),
                    ("geldi", "GELDI"),
                    ("gelmedi", "GELMEDI"),
                    ("sonra_gelecek", "SONRA GELECEK"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="reviewqueueitem",
            name="issue_type",
            field=models.CharField(
                choices=[
                    ("provider_not_detected", "Provider not detected"),
                    ("reference_missing", "Reference missing"),
                    ("date_missing", "Date missing"),
                    ("time_missing", "Time missing"),
                    ("traveler_count_missing", "Traveler count missing"),
                    ("lead_traveler_missing", "Lead traveler missing"),
                    ("provider_alias_missing", "Provider alias missing"),
                    ("product_mismatch", "Product mismatch"),
                    ("low_confidence_parse", "Low confidence parse"),
                    ("possible_duplicate", "Possible duplicate"),
                    ("manual_override_conflict", "Manual override conflict"),
                    ("cancellation_without_booking", "Cancellation without booking"),
                    ("parser_error", "Parser error"),
                ],
                max_length=40,
            ),
        ),
    ]
