# Generated by Django 5.2.15 on 2026-06-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_booking_attendance_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewqueueitem",
            name="issue_type",
            field=models.CharField(
                choices=[
                    ("provider_not_detected", "Provider not detected"),
                    ("reference_missing", "Reference missing"),
                    ("date_missing", "Date missing"),
                    ("time_missing", "Time missing"),
                    ("traveler_count_missing", "Traveler count missing"),
                    ("lead_traveler_missing", "Lead traveler missing"),
                    ("provider_alias_missing", "Provider alias missing"),
                    ("product_mismatch", "Product mismatch"),
                    ("low_confidence_parse", "Low confidence parse"),
                    ("possible_duplicate", "Possible duplicate"),
                    ("manual_override_conflict", "Manual override conflict"),
                    ("cancellation_without_booking", "Cancellation without booking"),
                    ("capacity_overbooked", "Capacity overbooked"),
                    ("parser_error", "Parser error"),
                ],
                max_length=40,
            ),
        ),
    ]
