# Generated by Django 5.2.15 on 2026-06-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_alter_bookingevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityschedule",
            name="timezone",
            field=models.CharField(default="Europe/Istanbul", max_length=80),
        ),
    ]
